### global variables
@baseUrl = http://localhost:3003
@contentType = application/json

@blogPath = /api/blogs

### get all
GET {{baseUrl}}{{blogPath}}

### add new blog
POST  {{baseUrl}}{{blogPath}}
Content-Type: {{contentType}}

{
    "title":"Node.js intro",
    "author":"root",
    "url":"http://localhost:3003/api/blogs/intro-node",
    "likes":  190,
    "userId": "5ee243d88aad501bcc08cee2"
}


### update existing blog
PUT  {{baseUrl}}{{blogPath}}/5ede272a6d21c0150838e8ec
Content-Type: {{contentType}}

{   
    "likes":999
}

### delete 
DELETE  {{baseUrl}}{{blogPath}}/5ede237a6d21c0150838e8eb

# {        
#     "title":"node.js the hard parts", 
#     "author":"mohamed sakr", 
#     "url":"http://localhost:3003/api/blogs/intro-nodejs", 
#     "likes":10
# }


# {       
#     "title":"test", 
#     "author":"test author", 
#     "url":"http://localhost:3003/api/blogs/test",
#     "likes":11
# }