### global variables
@baseUrl = http://localhost:3003
@contentType = application/json

@blogPath = /api/blogs

### get all
GET {{baseUrl}}{{blogPath}}

### add new blog
POST  {{baseUrl}}{{blogPath}}
Content-Type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZWUyM2IxZTQ0YjVhMjFmNTg1MWZhYTQiLCJpYXQiOjE1OTE5NTUyNDl9.b27zJF1Qmu9v7UAQDLiEJ6dSWgJXLXO9YYIm3_vAxBs

{
    "title":"token extractor middleware",
    "author":"root",
    "url":"http://localhost:3003/api/blogs/intro-node",
    "likes":  123400
}

# {
#     "title":"Node.js intro",
#     "author":"root",
#     "url":"http://localhost:3003/api/blogs/intro-node",
#     "likes":  190,
#     "userId": "5ee243d88aad501bcc08cee2"
# }


### update existing blog likes ONLY
PUT  {{baseUrl}}{{blogPath}}/5ee3818b076569150c3c9a10
Content-Type: {{contentType}}

# {   
#     "likes":999
# }

### delete existing blog
DELETE  {{baseUrl}}{{blogPath}}/5ee3818b076569150c3c9a10
# Content-Type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVlZTI0M2Q4OGFhZDUwMWJjYzA4Y2VlMiIsImlhdCI6MTU5MTk2OTc2MX0.PMJpn5_8RoLS-M5am3aF84VbCJoLuytYW10sYGbLUJA

#  {
#     "_id": "5ee3818b076569150c3c9a10",
#     "title": "token extractor middleware",
#     "author": "root",
#     "url": "http://localhost:3003/api/blogs/intro-node",
#     "likes": 123400,
#     "user": "5ee23b1e44b5a21f5851faa4",
#     "__v": 0
#   }
##################################

# {        
#     "title":"node.js the hard parts", 
#     "author":"mohamed sakr", 
#     "url":"http://localhost:3003/api/blogs/intro-nodejs", 
#     "likes":10
# }

#######################################
# {       
#     "title":"test", 
#     "author":"test author", 
#     "url":"http://localhost:3003/api/blogs/test",
#     "likes":11
# }