### global variables
@baseUrl = http://localhost:3003
@contentType = application/json

@loginPath = /api/login



### user login 
POST  {{baseUrl}}{{loginPath}}
Content-Type: {{contentType}}

{        
    "username": "root",
    "password": "salainen"
}

# {        
#     "username": "mluukkai",
#     "password": "salainen"
# }